version: 2

jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Build
          command: npm run build
      - run:
          name: Lint
          command: npm run lint
