version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    environment:
      # change the npm config to avoid using sudo
      NPM_CONFIG_PREFIX: ~/.npm-global
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Build
          command: npm run build
      - run:
          name: Lint
          command: npm run check-lint
