name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci && npm link && npm link eslint-plugin-caleb
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run check-lint
      - name: Clone Peregrine
        run: git clone https://github.com/Pigmice2733/peregrine-frontend
      - name: Install Peregrine
        run:
          cd peregrine-frontend && git checkout eslint-fixes; npm ci && npm link
          eslint-plugin-caleb
      - name: Lint Peregrine
        run: cd peregrine-frontend && npm run check-lint
